### ISSUE TITLE
Error: req.flash() requires sessions

### ISSUE THREAD

**Issue by Cronick** [chrismpettyjohn/xhabbo-node#1]
I start the application with node index.js and this error seems to popup every time.

`Error: req.flash() requires sessions
   at Error (native)
   at IncomingMessage._flash [as flash] (C:\Users\Cronick\Documents\GitHub\xhabbo-node\node_modules\connect-flash\lib\flash.js:60:41)
   at C:\Users\Cronick\Documents\GitHub\xhabbo-node\app\http\controllers\login.js:6:25
   at Layer.handle [as handle_request] (C:\Users\Cronick\Documents\GitHub\xhabbo-node\node_modules\express\lib\router\layer.js:95:5)
   at next (C:\Users\Cronick\Documents\GitHub\xhabbo-node\node_modules\express\lib\router\route.js:131:13)
   at Route.dispatch (C:\Users\Cronick\Documents\GitHub\xhabbo-node\node_modules\express\lib\router\route.js:112:3)
   at Layer.handle [as handle_request] (C:\Users\Cronick\Documents\GitHub\xhabbo-node\node_modules\express\lib\router\layer.js:95:5)
   at C:\Users\Cronick\Documents\GitHub\xhabbo-node\node_modules\express\lib\router\index.js:277:22
   at Function.process_params (C:\Users\Cronick\Documents\GitHub\xhabbo-node\node_modules\express\lib\router\index.js:330:12)
   at next (C:\Users\Cronick\Documents\GitHub\xhabbo-node\node_modules\express\lib\router\index.js:271:10)
   at C:\Users\Cronick\Documents\GitHub\xhabbo-node\app\http\middleware\install-check.js:8:14
   at Layer.handle [as handle_request] (C:\Users\Cronick\Documents\GitHub\xhabbo-node\node_modules\express\lib\router\layer.js:95:5)
   at trim_prefix (C:\Users\Cronick\Documents\GitHub\xhabbo-node\node_modules\express\lib\router\index.js:312:13)
   at C:\Users\Cronick\Documents\GitHub\xhabbo-node\node_modules\express\lib\router\index.js:280:7
   at Function.process_params (C:\Users\Cronick\Documents\GitHub\xhabbo-node\node_modules\express\lib\router\index.js:330:12)
   at next (C:\Users\Cronick\Documents\GitHub\xhabbo-node\node_modules\express\lib\router\index.js:271:10)`

**Comment by chrismpettyjohn** [comment]
The current version requires Redis to be installed, and this is not designed to be ran yet on production or used at all ideally until release 1 is made
